[project]
authors = ["Jermiah <jermiahjoseph98@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "update_pset_pipeline"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install_pgx = {cmd = """
Rscript -e "pak::pkg_install('bhklab/PharmacoGx')"
"""}

[dependencies]
r-base = ">=4.4.1,<5"
r-essentials = ">=4.4,<5"
"r-data.table" = ">=1.15.4,<2"
r-pak = ">=0.8.0,<0.9"
radian = ">=0.6.13,<0.7"
r-qs = ">=0.26.3,<0.27"

